// <auto-generated />
using Daxus_FootballManagement.DAL.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Daxus_FootballManagement.DAL.Migrations
{
    [DbContext(typeof(DaxusContext))]
    [Migration("20180214082630_AddedTeamsAndChangedOldModels")]
    partial class AddedTeamsAndChangedOldModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Daxus_FootballManagement.DAL.Model.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PlayerFkId");

                    b.Property<double>("Salary");

                    b.Property<int?>("TeamFkId");

                    b.Property<DateTime>("ValidFrom");

                    b.Property<DateTime>("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("PlayerFkId");

                    b.HasIndex("TeamFkId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Daxus_FootballManagement.DAL.Model.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Daxus_FootballManagement.DAL.Model.GuestSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GuestId");

                    b.Property<int?>("PlayerFkId");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("PlayerFkId");

                    b.ToTable("GuestSlot");
                });

            modelBuilder.Entity("Daxus_FootballManagement.DAL.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Daxus_FootballManagement.DAL.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Tier");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Daxus_FootballManagement.DAL.Model.Contract", b =>
                {
                    b.HasOne("Daxus_FootballManagement.DAL.Model.Player", "PlayerFk")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerFkId");

                    b.HasOne("Daxus_FootballManagement.DAL.Model.Team", "TeamFk")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamFkId");
                });

            modelBuilder.Entity("Daxus_FootballManagement.DAL.Model.GuestSlot", b =>
                {
                    b.HasOne("Daxus_FootballManagement.DAL.Model.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Daxus_FootballManagement.DAL.Model.Player", "PlayerFk")
                        .WithMany("GuestSlots")
                        .HasForeignKey("PlayerFkId");
                });
#pragma warning restore 612, 618
        }
    }
}
